FROM salon_loaders

ARG TOKEN

USER root
RUN apk add --no-cache ca-certificates && update-ca-certificates && \
  wget -O /microscanner https://get.aquasec.com/microscanner && \
  chmod +x /microscanner && \
  /microscanner ${TOKEN} && \
rm -rf /microscanner
